config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "countries#index"

  resources :countries do
    get :state, on: :member
    collection do
      post 'import'
    end
  end

  resources :states do
    collection do
      post 'import'
    end
  end
  resources :cities do
  collection do
      post 'import'
    end
  end
  get '/states/:country_id/fetch_states', to: 'states#fetch_states'
  get '/countries/:country_id/status', to: 'countries#status'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
   acts_as_paranoid
  belongs_to :country
  belongs_to :state
  validates :name, presence: true
  scope :active, -> { where(is_active: true) }
  scope :inactive, -> { where(is_active: false) } 
  
  require 'csv'
  def self.to_csv
    cities = all
    CSV.generate do |csv|
    csv << column_names
     cities.each do |city|
     csv << city.attributes.values_at(*column_names)
    end
   end
  end

  def self.import_from_csv(file)
    CSV.foreach(file.path, headers: true) do |row|
      city_hash = {}
      city_hash[:name] = row['name']
      city_hash[:country_id] = row['country_id']
      city_hash[:state_id] = row['state_id']
      city_hash[:is_active] = row['is_active']

      City.find_or_create_by!(city_hash)
    end
  end 
end

app/models/country.rb
class Country < ApplicationRecord
  acts_as_paranoid
  has_many :states, dependent: :destroy
  has_many :cities, dependent: :destroy
  validates :name, presence: true
  scope :active, -> { where(is_active: true) }
  scope :inactive, -> { where(is_active: false) } 
  
  require 'csv'
  def self.to_csv
    countries = all
    CSV.generate do |csv|
    csv << column_names
     countries.each do |country|
     csv << country.attributes.values_at(*column_names)
    end
   end
  end

  def self.import_from_csv(file)
    CSV.foreach(file.path, headers: true) do |row|
      country_hash = {}
      country_hash[:name] = row['name']
      country_hash[:is_active] = row['is_active']

      Country.find_or_create_by!(country_hash)
    end
  end
end

app/models/state.rb
class State < ApplicationRecord
   acts_as_paranoid
  belongs_to :country
  has_many :cities, dependent: :destroy
  validates :name, :abbreviation, presence: true
  scope :active, -> { where(is_active: true) }
  scope :inactive, -> { where(is_active: false) } 
  
  require 'csv'
  def self.to_csv
    states = all
    CSV.generate do |csv|
    csv << column_names
     states.each do |state|
     csv << state.attributes.values_at(*column_names)
    end
   end
  end

  def self.import_from_csv(file)
    CSV.foreach(file.path, headers: true) do |row|
      state_hash = {}
      state_hash[:name] = row['name']
      state_hash[:abbreviation] = row['abbreviation']
      state_hash[:country_id] = row['country_id']
      state_hash[:is_active] = row['is_active']

      State.find_or_create_by!(state_hash)
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @cities = City.all
    respond_to do |format|
      format.html
      format.json { render json: CityDatatable.new(params, view_context: view_context) }
      format.csv { send_data City.to_csv, filename: "cities-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
    end
  end

 def import
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    City.import_from_csv(params[:file])

    redirect_to request.referer, notice: 'Import started...'
 end
 
  def show
    @city = City.find(params[:id])
  end
 
  def new
    @city = City.new
  end
 
  def edit
    @city = City.find(params[:id])
  end
 
  def create
    @city = City.new(city_params)
 
    if @city.save
      redirect_to @city
    else
      render 'new'
    end
  end
 
  def update
    @city = City.find(params[:id])
 
    if @city.update(city_params)
      redirect_to @city
    else
      render 'edit'
    end
  end
 
  def destroy
    @city = City.find(params[:id])
    @city.destroy
 
    redirect_to cities_path
  end
 
  private
    def city_params
      params.require(:city).permit(:name, :is_active, :country_id, :state_id)
    end
  
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index
    @countries = Country.all
    respond_to do |format|
      format.html
      format.json { render json: CountryDatatable.new(params, view_context: view_context) }
      format.csv { send_data Country.to_csv, filename: "countries-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
    end
  end

  def import
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    Country.import_from_csv(params[:file])

    redirect_to request.referer, notice: 'Import started...'
  end

  def show
    @country = Country.find(params[:id])
  end
 
  def new
    @country = Country.new
  end
 
  def edit
    @country = Country.find(params[:id])
  end
 
  def create
    @country = Country.new(country_params)
 
    if @country.save
      redirect_to @country
    else
      render 'new'
    end
  end
 
  def update
    @country = Country.find(params[:id])
 
    if @country.update(country_params)
      redirect_to @country
    else
      render 'edit'
    end
  end
 
  def destroy
    @country = Country.find(params[:id])
    @country.destroy
 
    redirect_to countries_path
  end

  def status
    raise params.inspect
    country = Country.active
    country = Country.inactive

    render json: { countries: country }
  end

  private
    def country_params
      params.require(:country).permit(:name, :is_active)
    end
  
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  def index
    @states = State.all
    respond_to do |format|
      format.html
      format.json { render json: StateDatatable.new(params, view_context: view_context) }
      format.csv { send_data State.to_csv, filename: "states-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
    end
  end

  def import
    return redirect_to request.referer, notice: 'No file added' if params[:file].nil?
    return redirect_to request.referer, notice: 'Only CSV files allowed' unless params[:file].content_type == 'text/csv'

    State.import_from_csv(params[:file])

    redirect_to request.referer, notice: 'Import started...'
  end
 
  def show
    @state = State.find(params[:id])
  end
 
  def new
    @state = State.new
  end
 
  def edit
    @state = State.find(params[:id])
  end
 
  def create
    @state = State.new(state_params)
 
    if @state.save
      redirect_to @state
    else
      render 'new'
    end
  end
 
  def update
    @state = State.find(params[:id])
 
    if @state.update(state_params)
      redirect_to @state
    else
      render 'edit'
    end
  end
 
  def destroy
    @state = State.find(params[:id])
    @state.destroy
 
    redirect_to states_path
  end

  def fetch_states
    country = Country.find(params[:country_id])
    states = country.states

    render json: { states: states }
  end
 
  private
    def state_params
      params.require(:state).permit(:name, :abbreviation, :is_active, :country_id)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/cities/_form.html.erb
<%= form_with model: @city do |form| %>
 
   <div class="mb-3 row">
  <%= form.label :country, class:"col-sm-2 col-form-label" %>
  <div class = "col-lg-9">
   <%= form.collection_select :country_id, Country.order(:name), :id, :name, { prompt: 'Select a Country' }, {id: 'country-select', class: "form-select" } %>
  </div>
  <% @city.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
  <% end %>
  </div>

   <div class="mb-3 row">
  <%= form.label :state, class:"col-sm-2 col-form-label" %>
  <div class = "col-lg-9">
    <%= form.collection_select :state_id, State.order(:name), :id, :name, { prompt: 'Select a State' }, { id: 'state-select', class: "form-select" } %>
  </div>
  <% @city.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
  <% end %>
  </div>

   <div class="mb-3 row">
    <%= form.label :name, class:"col-sm-2 col-form-label" %>
    <div class = "col-lg-9">
    <%= form.text_field :name, class:"form-control" %>
  </div>
    <% @city.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3 row">
    <%= form.label :active, class:"col-sm-2 col-form-label" %>
    <div class = "col-lg-9">
    <%= form.check_box :is_active, class:"mb-2 form-check-input" %><br>
  </div>
    <% @city.errors.full_messages_for(:is_active).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
     $(document).ready(function() {
     $('#country-select').change(function() {
       var selectedCountryId = $(this).val();
       var stateField = $('#state-field');
       var stateSelect = $('#state-select');
       if (selectedCountryId !== '') {
          $.ajax({
            url: '/states/' + selectedCountryId + '/fetch_states',
            type: 'GET',
            dataType: 'json',
            success: function(data) {
              stateSelect.empty();
              $.each(data.states, function(index, state) {
                stateSelect.append('<option value="' + state.id + '">' + state.name + '</option>');
              });
                  stateField.show();
            },
                error: function(error) {
                console.error('Error:', error);
                }
              });
            } else {
                stateSelect.empty();
                stateField.hide();
              }
            });
          });
 </script>
  <div>
    <%= form.submit"Create City", class:"btn btn-primary mt-2 mb-2" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Edit City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path, class:"btn btn-success" %>

app/views/cities/index.html.erb
<div class="content">
<div class="card">
  <div class="card-header d-md-flex">
     <h5 class="mb-0">City</h5>
     <div class="collapse d-lg-block my-lg-auto ms-lg-auto">
      <%= link_to 'New City', new_city_path, class: "btn btn-warning me-3", style: 'color:black' %>
      <%= link_to "Export to csv", cities_path(format: 'csv'), class: "btn btn-success", style: 'color:white' %>
     </div>
  </div>
<table class="table" id="cities-datatable" data-source="<%= cities_path(format: :json) %>">
 <thead>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th>State</th>
    <th>Active</th>
    <th class="text-center" data-orderable="false">Actions</th>
  </tr>
 </thead>

 <tbody>

 </tbody>
</table>
</div>
</div>
<%= form_tag import_cities_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag '⚙️ Import' %>
<% end %>

app/views/cities/new.html.erb
<div class="content">
 <div class="card ps-3 py-2">
<h1>New City</h1>

<%= render 'form' %>

</div>
<%= link_to 'Back', cities_path, class:"btn btn-success" %>
</div>

app/views/cities/show.html.erb
<strong class="fs-5">Name:</strong>
<%= @city.name %></br>

<strong class="fs-5">Country:</strong>
<%= @city.country.name %></br>

<strong class="fs-5">State:</strong>
<%= @city.state.name %></br>

<strong class="fs-5">Active:</strong>
<%= @city.is_active %></br>

<%= link_to 'Edit', edit_city_path(@city), class:"btn btn-warning" %>
<%= link_to 'Back', cities_path, class:"btn btn-success ms-4" %>

app/views/countries/_form.html.erb
<%= form_with model: @country do |form| %>
  <div class="mb-3 row">
    <%= form.label :name, class:"col-sm-2 col-form-label" %>
    <div class = "col-lg-9">
    <%= form.text_field :name, class:"form-control", placeholder: "Enter your name.." %>
    </div>
    <% @country.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3 row">
    <%= form.label :active, class:"col-sm-2 col-form-label"  %>
    <div class = "col-lg-9">
    <%= form.check_box :is_active, class:"mb-2 form-check-input" %><br>
  </div>
    <% @country.errors.full_messages_for(:is_active).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit"Create Country", class:"btn btn-primary mt-2 mb-2" %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Edit Country</h1>

<%= render 'form' %>

<%= link_to 'Back', countries_path, class:"btn btn-success" %>

app/views/countries/index.html.erb
<div class="content">
<div class="card">
  <div class="card-header d-md-flex ">
    <h5 class="mb-0">Country</h5>
    <div class="collapse d-lg-block my-lg-auto ms-lg-auto">
     <%= link_to 'New country', new_country_path, class: "btn btn-warning me-3", style: 'color:black' %>
     <%= link_to "Export to csv", countries_path(format: 'csv'), class: "btn btn-success me-3", style: 'color:white' %>
    </div>
  </div>
<table class="table" id="countries-datatable" data-source="<%= countries_path(format: :json) %>">
 <thead>
  <tr>
    <th>Name</th>
    <th>Active</th>
    <th class="text-center">Actions</th>
  </tr>
 </thead>
 <tbody>
  
 </tbody>
</table>
</div>
</div>
<%= form_tag import_countries_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag '⚙️ Import' %>
<% end %>

app/views/countries/new.html.erb
<div class="content">
 <div class="card ps-3 py-2">
<h1>New Country</h1>

<%= render 'form' %>

</div>
<%= link_to 'Back', countries_path, class:"btn btn-success" %>
</div>

app/views/countries/show.html.erb
<strong class="fs-5">Name:</strong>
<%= @country.name %></br>

<strong class="fs-5">Active:</strong>
<%= @country.is_active %></br>

<%= link_to 'Edit', edit_country_path(@country), class:"btn btn-warning" %>
<%= link_to 'Back', countries_path, class:"btn btn-success ms-4" %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-sm navbar-footer border-top">
	<div class="container-fluid">
		<span>&copy; <%= Time.now.utc.year %></span>
		<%= link_to "Country selector", root_path %>
	</div>
</div>

app/views/layouts/_main_navbar.html.erb
<div class="navbar navbar-dark navbar-expand-lg navbar-static border-bottom border-bottom-white border-opacity-10">
	<div class="container-fluid">
		<div class="d-flex d-lg-none me-2">
			<button type="button" class="navbar-toggler sidebar-mobile-main-toggle rounded-pill">
				<i class="ph-list"></i>
			</button>
		</div>
		<div class="navbar-brand flex-1 flex-lg-0">
			<a href="#" class="d-inline-flex align-items-center">
				<%= image_tag "logo_icon.svg", alt: "logo_icon.svg" %>
				<%= link_to "Details", root_path, class:"fs-5 fw-bold ps-3 text-white" %>
			</a>
		</div>
		<ul class="nav flex-row justify-content-end order-1 order-lg-2">
			<li class="nav-item nav-item-dropdown-lg dropdown ms-lg-2">
				<a href="#" class="navbar-nav-link align-items-center rounded-pill p-1" data-bs-toggle="dropdown">
					<div class="status-indicator-container">
						<%= image_tag "face11.jpg", class: "w-32px h-32px rounded-pill", alt: "face11.jpg" %>
						<span class="status-indicator bg-success"></span>
					</div>
					<span class="d-none d-lg-inline-block mx-lg-2">Victoria</span>
				</a>
				<div class="dropdown-menu dropdown-menu-end">
					<a href="#" class="dropdown-item">
						<i class="ph-user-circle me-2"></i>
						My profile
					</a>
					<a href="#" class="dropdown-item">
						<i class="ph-currency-circle-dollar me-2"></i>
						My subscription
					</a>
					<a href="#" class="dropdown-item">
						<i class="ph-shopping-cart me-2"></i>
						My orders
					</a>
					<a href="#" class="dropdown-item">
						<i class="ph-envelope-open me-2"></i>
						My inbox
						<span class="badge bg-primary rounded-pill ms-auto">26</span>
					</a>
					<div class="dropdown-divider"></div>
					<a href="#" class="dropdown-item">
						<i class="ph-gear me-2"></i>
						Account settings
					</a>
				</div>
			</li>
		</ul>
	</div>
</div>

app/views/layouts/_main_sidebar.html.erb
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-lg">
	<!-- Sidebar content -->
	<div class="sidebar-content">
		<!-- Sidebar header -->
		<div class="sidebar-section">
			<div class="sidebar-section-body d-flex justify-content-center">
				<h5 class="sidebar-resize-hide flex-grow-1 my-auto">Navigation</h5>
				<div>
					<button type="button" class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-control sidebar-main-resize d-none d-lg-inline-flex">
						<i class="ph-arrows-left-right"></i>
					</button>
					<button type="button" class="btn btn-flat-white btn-icon btn-sm rounded-pill border-transparent sidebar-mobile-main-toggle d-lg-none">
						<i class="ph-x"></i>
					</button>
				</div>
			</div>
		</div>
		<!-- /sidebar header -->
		<!-- Main navigation -->
		<div class="sidebar-section">
			<ul class="nav nav-sidebar" data-nav-type="accordion">
				<!-- Main -->
				<li class="nav-item-header pt-0">
					<div class="text-uppercase fs-sm lh-sm opacity-50 sidebar-resize-hide">Main</div>
					<i class="ph-dots-three sidebar-resize-show"></i>
				</li>
				<li class="nav-item">
				  <%= link_to '<i class="ph-house"></i> Country'.html_safe, countries_path, class:"nav-link" %>
				</li>
				<li class="nav-item">
				  <%= link_to '<i class="ph-house"></i> State'.html_safe, states_path, class:"nav-link" %>
				</li>
				<li class="nav-item">
				  <%= link_to '<i class="ph-house"></i> City'.html_safe, cities_path, class:"nav-link" %>
				</li>
				<!-- /main -->
			</ul>
		</div>
		<!-- /main navigation -->
	</div>
	<!-- /sidebar content -->
</div>

app/views/layouts/_page_header.html.erb
<div class="page-header page-header-light shadow">
	<div class="page-header-content d-lg-flex">
		<div class="d-flex">
			<h4 class="page-title mb-0">
				Tables - <span class="fw-normal">Blogs</span>
			</h4>
		</div>
	</div>
	<div class="page-header-content d-lg-flex border-top">
		<div class="d-flex">
			<div class="breadcrumb py-2">
				<span class="breadcrumb-item active"><i class="ph-house"></i></span>
				<span class="breadcrumb-item">Blogs</span>
				<span class="breadcrumb-item active">Basic examples</span>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Details</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Main navbar -->
    <%= render "layouts/main_navbar" %>
    <!-- /main navbar -->
    <!-- Page content -->
    <div class="page-content">
      <!-- Main sidebar -->
      <%= render "layouts/main_sidebar" %>
      <!-- /main sidebar -->
      <!-- Main content -->
      <div class="content-wrapper">
        <!-- Inner content -->
        <div class="content-inner">
          <!-- Page header -->
          <%= render "layouts/page_header" %>
          <!-- /page header -->
          <!-- Content area -->
          <div class="content">
            <%= yield %>
          </div>
          <!-- /content area -->
          <!-- Footer -->
          <%= render "layouts/footer" %>
          <!-- /footer -->
        </div>
        <!-- /inner content -->
      </div>
      <!-- /main content -->
    </div>
    <!-- /page content -->
  </body>
</html>

app/views/states/_form.html.erb
<%= form_with model: @state do |form| %>
  <div class="mb-3 row">
    <%= form.label :name, class:"col-sm-2 col-form-label" %>
    <div class = "col-lg-9">
    <%= form.text_field :name, class:"form-control" %>
  </div>
    <% @state.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3 row">
    <%= form.label :abbreviation, class:"col-sm-2 col-form-label" %>
    <div class = "col-lg-9">
    <%= form.text_field :abbreviation, class:"form-control" %><br>
  </div>
    <% @state.errors.full_messages_for(:abbreviation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div class="mb-3 row">
  <%= form.label :country, class:"col-sm-2 col-form-label" %>
  <div class = "col-lg-9">
   <%= form.collection_select :country_id, Country.order(:name), :id, :name, { prompt: 'Select a Country' }, { id: 'country-select', class: "form-select" } %>
  </div>
  <% @state.errors.full_messages_for(:abbreviation).each do |message| %>
    <div><%= message %></div>
  <% end %>
  </div>

   <div class="mb-3 row">
    <%= form.label :active, class:"col-sm-2 col-form-label" %>
    <div class = "col-lg-9">
    <%= form.check_box :is_active, class:"mb-2 form-check-input" %><br>
  </div>
    <% @state.errors.full_messages_for(:is_active).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit"Create State", class:"btn btn-primary mt-2 mb-2" %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Edit State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path, class:"btn btn-success" %>

app/views/states/index.html.erb
<div class="content">
<div class="card">
  <div class="card-header d-md-flex ">
    <h5 class="mb-0">State</h5>
    <div class="collapse d-lg-block my-lg-auto ms-lg-auto">
     <%= link_to 'New state', new_state_path, class: "btn btn-warning me-3", style: 'color:black' %>
     <%= link_to "Export to csv", states_path(format: 'csv'), class: "btn btn-success", style: 'color:white' %>
    </div>
  </div>
<table class="table" id="states-datatable" data-source="<%= states_path(format: :json) %>">
 <thead>
  <tr>
    <th>Name</th>
    <th>Abbreviation</th>
    <th>Country</th>
    <th>Active</th>
    <th class="text-center" data-orderable="false">Actions</th>
  </tr>
 </thead>

 <tbody>
  
 </tbody>
</table>
</div>
</div>
<%= form_tag import_states_path, method: :post, multipart: true do %>
  <%= file_field_tag :file, accept: ".csv" %>
  <%= submit_tag '⚙️ Import' %>
<% end %>

app/views/states/new.html.erb
<div class="content">
 <div class="card ps-3 py-2">

<h1>New State</h1>

<%= render 'form' %>

</div>

<%= link_to 'Back', states_path, class:"btn btn-success" %>

</div>

app/views/states/show.html.erb
<strong class="fs-5">Name:</strong>
<%= @state.name %></br>

<strong class="fs-5">Abbreviation:</strong>
<%= @state.abbreviation %></br>

<strong class="fs-5">Country:</strong>
<%= @state.country.name %></br>

<strong class="fs-5">Active:</strong>
<%= @state.is_active %></br>


<%= link_to 'Edit', edit_state_path(@state), class:"btn btn-warning" %>
<%= link_to 'Back', states_path, class:"btn btn-success ms-4" %>